version: '3.3'
services:
    db:
        image: postgres:11.1-alpine
        environment:
          - POSTGRES_DB=tripy
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=password
        ports:
          - "5432:5432"
    php:
        build: ./php-fpm
        ports:
            - "9000:9001"
        volumes:
            - ../Tripy:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
        links:
            - db
        extra_hosts:
            - "docker-host.localhost:127.0.0.1"
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ../Tripy:/var/www/symfony:cached
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./elk/logstash:/etc/logstash:cached
            - ./elk/logstash/patterns:/opt/logstash/patterns:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./logs/nginx:/var/log/nginx:cached
